package model;

public class Customer {
	int customerID;
	String customerName;
	String address;
	String postalCode;
	String phone;
	int divisionID;
	String divisionName;

	public Customer(int customerID, String customerName, String address, String postalCode, String phone, int divisionID, String divisionName) {
		this.customerID = customerID;
		this.customerName = customerName;
		this.address = address;
		this.postalCode = postalCode;
		this.phone = phone;
		this.divisionID = divisionID;
		this.divisionName = divisionName;
	}

	public int getCustomerID() {
		return customerID;
	}

	public void setCustomerID(int customerID) {
		this.customerID = customerID;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public int getDivisionID() {
		return divisionID;
	}

	public void setDivisionID(int divisionID) {
		this.divisionID = divisionID;
	}

	public String getDivisionName() {
		return divisionName;
	}

	public void setDivisionName(String divisionName) {
		this.divisionName = divisionName;
	}
}


// When deleting a customer record, all customer appointments must be deleted first due to the foreign key constraint.

// When adding/updating a customer, collect customer name, address, postal code, phone number using TextFields.
// Address field should not include first level division and country data
// US address: 123 ABC Street, White Plains
// CA address: 123 ABC Street, Newmarket
// UK address: 123 ABC Street, Greenwich, London


// Customer IDs are auto-generated by the database.

// First Level Division and country data are collected using ComboBoxes.